### ISSUE TITLE
Recreate directory structure

### ISSUE THREAD

**Issue by alexshk** [gtg092x/gulp-sftp#15]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: No such file
```

Thanks

**Comment by tomoakley** [comment]
Hi - I have this problem too. I use Gulp with WordPress themes, and have some custom directories (e.g assets/images, etc). Whenever gulp-sftp comes across one of these, it just errors with the above that @davismj posted originally. Also, is it possible to have a file like .gitignore where I can specify files I don't want to upload? Currently, gulp-sftp is uploading everything, including the node_modules directory, which is *massive*.
