### ISSUE TITLE
directory separators on windows

### ISSUE THREAD

**Issue by valan** [gtg092x/gulp-sftp#2]
I think this might be a directory separator thing.

in gulpfile:

```
gulp.task('deploy-sftp', function() {
    return gulp.src('./deploy.zip')
        .pipe(sftp({
            host: "XXXXXX",
            remotePath: "/var/www/html",
            auth: 'stage'
        }));
});
```

in .ftppass:

```
{
    "stage": {
        "user": "ec2-user",
        "key": "C:/Dropbox/.ssh/id_rsa"
    }
}
```

result on server:
new file in /home/ec2-user with the filename: "\var\www\html\deploy.zip" (backslashes are part of the filename) 0 bytes

**Comment by kishu27** [comment]
I was having this issue in Mac OS X (Yosemite). So it's not just a windows thing. The problem got solved after I remove trailing `/` character from `remotePath` .
