### ISSUE TITLE
Creating remote folders ...

### ISSUE THREAD

**Issue by klwemu** [gtg092x/gulp-sftp#22]
Folders wich do not exist remtely can´t be created.

**Comment by klwemu** [comment]
Sorry, but it does not work.  The problem happens on new sub folders. 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: No such file  at SFTP._parse (C:\xampp\htdocs\vx\node_modules\gulp-sftp\node_modules\ssh2\lib\SFTP\SFTPv3.js:1090:23)
    at ChannelStream.<anonymous> (C:\xampp\htdocs\vx\node_modules\gulp-sftp\node_modules\ssh2\lib\SFTP\SFTPv3.js:72:10)
    at ChannelStream.emit (events.js:95:17)

**Comment by gtg092x** [comment]
@klwemu - can I get the OS of your local and remote operating system? This, as well as the remotePath parameter you're using in your gulp config.

**Comment by klwemu** [comment]
Hello, local is W8.1 and remote is Ubuntu.  
"remotePath": "/usr/share/nginx/html"

Err case: When we have a new folder (for a blog posting) in  ..nginx/html/blog/**newFolder**  the err raises. I hope this help´s

**Comment by gtg092x** [comment]
Does "blog" exist?

**Comment by klwemu** [comment]
yes! Only the sub folder is new ...

2015-02-10 19:06 GMT+01:00 Matthew Drake <notifications@github.com>:

> Does "blog" exist?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gtg092x/gulp-sftp/issues/22#issuecomment-73750261>.
>



-- 

Klaus Muckenhuber
Business Developement

https://VISITLEAD.com
0049 7247 50315 - 11
