### ISSUE TITLE
How to work with pem

### ISSUE THREAD

**Issue by unbug** [gtg092x/gulp-sftp#27]
I am using [pem](https://github.com/andris9/pem) to create private keys and certificates for this plugin.
Such as: 
```

var pem = require('pem');
gulp.task('deploy_test', function(cb) {
    pem.createCertificate({}, function (e, r) {
        return gulp.src(distPath+'*')
            .pipe(sftp({
                host: '172.28.2.33',
                port: 22,
                user: 'myname',
                pass: 'mypass',
                secure: true,
                key: r.clientKey,
                cert: r.certificate,
            }));
    });
});
```
Can it be possible?

**Comment by gtg092x** [comment]
Never tested it, but you should be able to use `keyContents` - this also looks like the wrong name to use! I'll make an update that uses the parameter `cert`. `keyContents` will remain for legacy reasons, but cert will be used in the future.

For now, use `keyContents`

**Comment by unbug** [comment]
Thank you,can you give pem a test?I can find any grunt or gulp plugin support this.

**Comment by unbug** [comment]
Change to `keyContents` works very well ;),please keep `keyContents` after use `cert`.

**Comment by gtg092x** [comment]
That's the plan. Thanks!

**Comment by unbug** [comment]
I‘ve fire you a PR for work with pem sample.
