### ISSUE TITLE
Empty folders

### ISSUE THREAD

**Issue by pyrsmk** [gtg092x/gulp-sftp#42]
Gulp-sftp seems to not upload empty directories (I'm uploading `cache/` and `uploads/` folders).

**Comment by gtg092x** [comment]
I'd recommend adding an empty and hidden file like .ftpkeep - if that doesn't work, please post an update

**Comment by pyrsmk** [comment]
I'm on windows, I can't simply do it ^^

**Comment by kaosmos** [comment]
actually you can :)
to create a file without name on Windows simply create a file named .whatnameyouwant. e.g. .htacess. and you'll get .htaccess

**Comment by pyrsmk** [comment]
I actually tried before saying it :p 
It requires me to enter a filename.

**Comment by kaosmos** [comment]
I'm sure you tried but still it actually works. Let me show it (it is an Italian Windows but it should be clear enough):

![filename without name in Windows](http://f.cl.ly/items/3E0p35120A1w3x2h1b1H/Screen%20Recording%202015-11-08%20at%204.15.22%20.gif)

**Comment by pyrsmk** [comment]
Ah! Didn't saw that dot at the end of the file, thanks!

**Comment by kaosmos** [comment]
you are welcome!

Matteo Nicoletti
Il 09/nov/2015 09:25, "Aurélien Delogu" <notifications@github.com> ha
scritto:
