### ISSUE TITLE
Support for custom private key file location

### ISSUE THREAD

**Issue by alatar-** [gtg092x/gulp-sftp#43]
Hi,

what about supporting custom private key file locations? Personally I have a couple of them and the one I need to use is not a default path (like `~/.ssh/id_rsa`). Would be useful to have an option parameter to specify the keyfile location.

What do you think? I could create a pull request.

Cheers

**Comment by christoshrousis** [comment]
Different to this or am I misinterpreting your question?

#### options.key

##### type String or Object Default: null

###### A key file location. If an object, please use the format {location:'/path/to/file',passphrase:'secretphrase'}

**Comment by alatar-** [comment]
Exactly. I had to truly overlook it. Thanks
