### ISSUE TITLE
Still have "gulp-sftp SFTP abrupt closure" error

### ISSUE THREAD

**Issue by breogangf** [gtg092x/gulp-sftp#49]
npm list ssh2

```
project@1.0.0 /Users/breogangf/Workspace/project
└─┬ gulp-sftp@0.1.5
  └── ssh2@0.3.6
```

Hi guys,

I am on Mac OS X 10.11.1 and my gulp-sftp fails with the following message:

```
14:43:35] 'publish' errored after 352 ms
[14:43:35] Error in plugin 'gulp-sftp'
Message:
    Disconnected by host (PROTOCOL_ERROR): Packet integrity error.
Details:
    level: connection-ssh
    description: Packet integrity error.
    lang:
[14:43:35] Connection :: end
[14:43:35] gulp-sftp SFTP abrupt closure
[14:43:35] Connection :: close
```

I am doing a normal publish task to our NAS

```
gulp.task('publish', ['zip'], function () { 
    return gulp.src('./build/' + zipBaseName + '*' + zipExtension)
        .pipe(sftp({
            host: MY_NAS_IP,
            remotePath: MY_REMOTE_PATH,
            auth: NAS_AUTH
        }));
});
```

**Comment by littledu** [comment]
yes, me too

+1+1

**Comment by maximaldesign** [comment]
me too

**Comment by tkmoney** [comment]
+1

**Comment by williansmartins** [comment]
me too +1

**Comment by Rubenkl** [comment]
+1

**Comment by peacefulseeker** [comment]
Are you sure you have ability to connect to server via SFTP port 22? Check out in Filezilla first. 
Had the same issue, but the problem was that there were no option in my hosting tariff to connect via SFTP. Hope will be useful for somebody.

**Comment by jing2si** [comment]
Try set `options.timeout` a long time.

**Comment by thomasfrobieter** [comment]
+1 
Is there no possibility to simply trigger a reconnect on error? Basically it shouldn't stop the whole Gulp script, so if I hit save again, it should try the upload again.

**Comment by awadley-stoneriver** [comment]
+1 Still an issue

**Comment by thomasfrobieter** [comment]
Not sure why this is closed, the issue still persists.
