### ISSUE TITLE
Create Directory if not present

### ISSUE THREAD

**Issue by udayms** [gtg092x/gulp-sftp#9]
Can gulp-sftp create a directory if it doesn't exist on the remote? For some reason, when I run my code, the code breaks with the following error if the directory is not already existing on remote:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: No such file

**Comment by nickdunn** [comment]
I'm also having the same problem. Deploying from OSX to a MediaTemple grid server (presumably Unix not Windows!). 

    remotePath: '/html'

With the following error:

        [18:29:57] SFTP error or directory exists: Error: Failure /html

        events.js:72
                throw er; // Unhandled 'error' event
                      ^
        Error: No such file
            at SFTP._parse (/Users/nick/Sites/uxua/node_modules/gulp-sftp/node_modules/ssh2/lib/SFTP/SFTPv3.js:1090:23)
            at ChannelStream.<anonymous> (/Users/nick/Sites/uxua/node_modules/gulp-sftp/node_modules/ssh2/lib/SFTP/SFTPv3.js:72:10)
            at ChannelStream.emit (events.js:95:17)
            at ChannelStream.<anonymous> (_stream_readable.js:764:14)
            at ChannelStream.emit (events.js:92:17)
            at emitReadable_ (_stream_readable.js:426:10)
            at emitReadable (_stream_readable.js:422:5)
            at readableAddChunk (_stream_readable.js:165:9)
            at ChannelStream.Readable.push (_stream_readable.js:127:10)
            at Parser.<anonymous> (/Users/nick/Sites/uxua/node_modules/gulp-sftp/node_modules/ssh2/lib/Channel.js:102:25)

Using `0.1.4` from npm.

**Comment by gtg092x** [comment]
@nickdunn - I'll create a new issue for you on this. Your project root directory is not getting created? Can you verify that the destination is unix?

**Comment by chris-equis** [comment]
I am having the same promble using 0.1.4 client machine: OSX, server machine: Ubuntu 14.10, auth SSH keys

**Comment by WuJiangquan** [comment]
I set remotePath such as  "./pathA/pathB/pathC/",
but it throwed an error too " no such file".
Then I  found a **bug** at line 238

`fileDirs = fileDirs.filter(function(d) { return d.length >= remotePath.length && !mkDirCache[d]; [});`](https://github.com/gtg092x/gulp-sftp/blob/master/index.js#L238)

fileDirs's origin value was ["./pathA/pathB/pathC","./pathA/pathB","./pathA"]
and my remotePath was  "./pathA/pathB/pathC/"  
  "./pathA/pathB/pathC".length < "./pathA/pathB/pathC/".length always  .
so at last the fileDirs (filter result) is an empty array.
As a result , it won't run the function sftp.mkdir to create my remotePath ["./pathA/pathB/pathC/".](https://github.com/gtg092x/gulp-sftp/blob/master/index.js#L254)
At  last  it works when I set my remotePath as  "./pathA/pathB/pathC".

**Comment by Dan503** [comment]
Why close the issue just becuase you found a work around. this si still an issue with the core plugin.

Instead of just erroring, it would be far more user friendly if it created any directories that don't currently exist.

I'm on version 0.1.5 and still getting this issue.

**Comment by Dan503** [comment]
Oh actually never mind. I was hitting permission denied issues when trying to create the directory, so not an issue with the plugin.

**Comment by Dan503** [comment]
I take it back again. This is still an issue.

**Comment by markymcfly** [comment]
Make sure, you are using the DOCUMENT_ROOT for the "options.remotePath". 
To get the DOCUMENT_ROOT just run info.php on your server:

**info.php**:
`<?php 
  phpinfo();
?>`

**Comment by potapovnikita** [comment]
The same problem. I’m use Mac OS Sierra -> Linux centos

**Comment by iconicwp** [comment]
For anyone else facing this issue - I found the directory is not created if it has a trailing slash. Without a slash, it worked.

**Working**: `some/directory/structure`
**Not Working**: `some/directory/structure/`

**Comment by iconicwp** [comment]
Just noticed @WuJiangquan said the same thing, but hopefully this is more clear.
